server:
  port: 8100

logging:
  level:
    pl:
      kukla:
        krzys: debug

spring:
  application:
    name: 05-currency-convertion-service
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

#hystrix timeout
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
  #ribbon timeout
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
